# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Diffusion Models in Depth
author: Gregory Igor Sedykh

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/gregorysedykh/diffusion-models-in-depth/
  branch: master 

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
