# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Diffusion Models in Depth
author: Gregory Igor Sedykh

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Information about where the book exists on the web
repository:
  url: https://github.com/gregorysedykh/diffusion-models-in-depth/
  branch: master 

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath

bibtex_bibfiles:
  - sources.bib
